services:
  nginx:
    container_name: mathcom-nginx
    image: nginx:alpine-slim
    restart: always
    volumes:
      - ./config/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
      - astro
    labels:
      - traefik.enable=true
      - traefik.http.routers.astro.rule=Host(`${HOSTNAME:-localhost}`)
      - traefik.http.routers.astro.tls=true
      - traefik.http.routers.astro.tls.certresolver=le
      - traefik.docker.network=traefik

  astro:
    container_name: mathcom-astro
    build: 
      context: ../../../../
      dockerfile: ./docker/production/main/astro/Dockerfile
      args:
          - PUBLIC_API=$PUBLIC_API
          - PUBLIC_INTERNAL_API=$PUBLIC_INTERNAL_API
    restart: always
    networks:
      - traefik
      - astro

networks:
  traefik:
    driver: bridge
    name: traefik
    external: true
  astro:
    driver: bridge
    name: astro