version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    container_name: mathcom-wordpress
    restart: always
    working_dir: /var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
      # Custom theme
      - ./wordpress/mathcom:/var/www/html/wordpress/wp-content/themes/mathcom
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - wordpress

  db:
    image: mariadb:latest
    container_name: mathcom-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mathcom-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    networks:
      - wordpress
    depends_on:
      - db

  astro:
    container_name: mathcom-astro
    build: 
      context: ../
      dockerfile: ./docker/astro/Dockerfile
      args:
        - PUBLIC_API=$PUBLIC_API
    restart: always
    networks:
      - wordpress
  
  nginx:
    image: nginx:alpine-slim
    container_name: mathcom-nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - wordpress
    depends_on:
      - wordpress
      - phpmyadmin

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress:
    driver: bridge
