services:
  wordpress:
    image: wordpress:latest
    container_name: mathcom-wordpress
    restart: always
    working_dir: /var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        # Development environment
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ./wordpress/data:/var/www/html/wordpress
      # Custom theme
      - ./wordpress/mathcom:/var/www/html/wordpress/wp-content/themes/mathcom
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - wordpress

  db:
    image: mariadb:latest
    container_name: mathcom-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mathcom-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    networks:
      - wordpress
    depends_on:
      - db

  astro:
    container_name: mathcom-astro
    build:
      context: ../
      dockerfile: ./docker/astro/Dockerfile
      args:
        - PUBLIC_API=$PUBLIC_API
        - PUBLIC_INTERNAL_API=$PUBLIC_INTERNAL_API
    restart: always
    networks:
      - wordpress

  nginx:
    image: nginx:alpine-slim
    container_name: mathcom-nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - wordpress
    depends_on:
      - wordpress
      - phpmyadmin

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/logs/:/var/log/letsencrypt/:rw

  main_archive:
    image: wordpress:latest
    container_name: main_archive-wordpress
    restart: always
    working_dir: /var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME_ARCHIVE_MAIN}
    volumes:
      - ./wordpress/archive/main:/var/www/html/wordpress
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - wordpress

  gradmath_archive:
    image: wordpress:latest
    container_name: gradmath_archive-wordpress
    restart: always
    working_dir: /var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME_ARCHIVE_GRADMATH}
    volumes:
      - ./wordpress/archive/gradmath:/var/www/html/wordpress
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - wordpress

  amcs_archive:
    image: wordpress:latest
    container_name: amcs_archive-wordpress
    restart: always
    working_dir: /var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME_ARCHIVE_AMCS}
    volumes:
      - ./wordpress/archive/amcs:/var/www/html/wordpress
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - wordpress

  csit_archive:
    image: wordpress:latest
    container_name: csit_archive-wordpress
    restart: always
    working_dir: /var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME_ARCHIVE_CSIT}
    volumes:
      - ./wordpress/archive/csit:/var/www/html/wordpress
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - wordpress



volumes:
  wordpress_data:
  db_data:


networks:
  wordpress:
    driver: bridge
